/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import com.toedter.calendar.JCalendar;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.*;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mizanur Rahman
 */
public class DataSales extends javax.swing.JFrame {

    /**
     * Creates new form DataSales
     */
    public DataSales() {
        initComponents();
       // getContentPane().setBackground(Color.CYAN);
        selectedCombo();
        
        Toolkit t1=Toolkit.getDefaultToolkit();
        int w=(int)t1.getScreenSize().getWidth();
        int h=(int)t1.getScreenSize().getHeight();
        this.setSize(w, h);
        setIconimageMy();
        sid.setText(""+autoid());
        //txtdiscount.setText(""+0);
        cuDate();
        discountem();
       // getContentPane().setBackground(Color.white);
                
       
        //for color
         //getContentPane().setBackground(Color.white);
    }
    
    String setNameInTable(String m){
       String mm=null;
        try {
            myConnection();
            
            String name="select `pname` from `product` where `pid`='"+m+"'";
            rs2=st2.executeQuery(name);
            if(rs2.next())
            {
                mm=(rs2.getString(1));
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        return mm;
        
    }
    
    void discountem(){
        String a=txtdiscount.getText();
        if(a.isEmpty()){
            int b = 0;
        txtdiscount.setText(""+b);
        }
    }
    
    void setIconimageMy()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_nike_50px.png")));
    }
    int autoid(){
        int a = 0;
        try {
            
            myConnection();
            String m="SELECT `sid` FROM `sales` ORDER BY `sid` ASC";
            rs=st.executeQuery(m);
            while(rs.next()){
                a=rs.getInt(1);
                
                
            }
            a++;
        } catch (SQLException ex) {
            Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
        }
        return a;
    }
    
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    Statement st2=null;
    ResultSet rs2=null;
    static int productid;
     
    void myConnection()
    {
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost/javaproject", "root", "");
            st=con.createStatement();
            st2=con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    void selectedCombo()
    {
        try {
            pname.removeAllItems();
            myConnection();
            String name="SELECT `pname` FROM `product`";
            pname.addItem("Select");
            rs=st.executeQuery(name);
            while(rs.next())
            {
                pname.addItem(rs.getString(1));
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        uprice = new javax.swing.JTextField();
        quant = new javax.swing.JTextField();
        sadate = new com.toedter.calendar.JDateChooser();
        pname = new javax.swing.JComboBox();
        pid = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        panelID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        paidamount = new javax.swing.JTextField();
        due = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        search = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        enddate = new com.toedter.calendar.JDateChooser();
        jButton12 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nike Shoes Gallery");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sales Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 18), new java.awt.Color(0, 102, 51))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 24));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Product Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 107, -1));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Quantity");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, -1));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Unit Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, -1));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 60, -1));

        sid.setEditable(false);
        sid.setBackground(new java.awt.Color(0, 102, 51));
        sid.setForeground(new java.awt.Color(255, 255, 51));
        sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidActionPerformed(evt);
            }
        });
        jPanel1.add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 48, 220, 40));

        uprice.setForeground(new java.awt.Color(102, 102, 0));
        jPanel1.add(uprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 220, 32));

        quant.setBackground(new java.awt.Color(0, 102, 51));
        quant.setForeground(new java.awt.Color(255, 255, 51));
        quant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quantMouseClicked(evt);
            }
        });
        quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantActionPerformed(evt);
            }
        });
        quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantKeyTyped(evt);
            }
        });
        jPanel1.add(quant, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 161, 220, 40));

        sadate.setBackground(new java.awt.Color(0, 51, 51));
        sadate.setForeground(new java.awt.Color(255, 255, 51));
        jPanel1.add(sadate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 220, 30));

        pname.setBackground(new java.awt.Color(0, 51, 51));
        pname.setForeground(new java.awt.Color(255, 255, 51));
        pname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pname.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                pnamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        jPanel1.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 220, 37));
        jPanel1.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 80, 40));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Discount");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 70, 30));

        txtdiscount.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        txtdiscount.setForeground(new java.awt.Color(0, 102, 51));
        txtdiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdiscount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdiscountMouseClicked(evt);
            }
        });
        jPanel1.add(txtdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 220, 40));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 140, 570, 360);

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 510, 80, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL.No", "Product Name", "Date", "Quantity", "Price", "Discount", "Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(50, 100, 640, 340);

        jLabel7.setText("Bill no:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 70, 50, 14);
        jPanel2.add(panelID);
        panelID.setBounds(100, 70, 47, 20);

        jLabel9.setText("Date:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(410, 70, 36, 14);
        jPanel2.add(panelDate);
        panelDate.setBounds(450, 60, 74, 20);

        jLabel11.setText("Total");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(540, 440, 50, 30);
        jPanel2.add(totalAmount);
        totalAmount.setBounds(590, 440, 100, 30);

        jLabel10.setText("Paid");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(540, 480, 32, 14);

        jLabel12.setText("Due");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(540, 510, 32, 14);

        paidamount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paidamount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paidamount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paidamountMouseClicked(evt);
            }
        });
        paidamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paidamountKeyPressed(evt);
            }
        });
        jPanel2.add(paidamount);
        paidamount.setBounds(590, 470, 107, 28);

        due.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        due.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(due);
        due.setBounds(590, 500, 107, 30);

        jLabel13.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nike Shoes Gallery");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(144, 11, 297, 31);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(78, 48, 467, 0);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Hospital mor,Feni sadar,feni");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(160, 40, 270, 14);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_nike_50px.png"))); // NOI18N
        jPanel2.add(jLabel17);
        jLabel17.setBounds(140, 10, 50, 40);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(120, 62, 390, 10);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Print");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(60, 480, 30, 20);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_send_to_printer_32px.png"))); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(50, 450, 50, 50);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_erase_30px_1.png"))); // NOI18N
        jButton8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(130, 450, 50, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(660, 150, 730, 540);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 560, 80, 30);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 510, 90, 30);

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(110, 510, 51, 30);

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 0));
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(340, 560, 80, 30);

        jButton6.setText("DELLETE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(340, 510, 100, 30);

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(837, 99, 270, 0);

        search.setBackground(new java.awt.Color(0, 0, 255));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorder(null);
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        jPanel3.add(search);
        search.setBounds(1100, 70, 230, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_search_32px.png"))); // NOI18N
        jPanel3.add(jLabel15);
        jLabel15.setBounds(1060, 70, 30, 40);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(1100, 100, 230, 10);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Product Sales Data");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(380, 30, 570, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1410, 120);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_search_30px_2.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1100, 60, 50, 36);

        date1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        date1.setDateFormatString("d MMM , y");
        getContentPane().add(date1);
        date1.setBounds(120, 600, 240, 40);

        jButton9.setText("Yearly");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(480, 600, 80, 40);

        jButton10.setText("Date");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(350, 600, 55, 40);

        jButton11.setText("Monthly");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(410, 600, 73, 40);
        getContentPane().add(enddate);
        enddate.setBounds(120, 650, 240, 40);

        jButton12.setText("Show");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(360, 650, 80, 40);

        jLabel18.setText("Total Day");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(180, 690, 90, 40);

        jLabel20.setText("Total Day");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(120, 690, 90, 40);

        jButton13.setText("print");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(470, 660, 55, 23);

        setBounds(0, 0, 1427, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sp="SELECT `sid`,`sDate`,`pid`,`sQuantity`,`price`,`discount` FROM `sales`";
        ShowData(sp);
    }//GEN-LAST:event_jButton1ActionPerformed
    void ShowData(String data)
    {
        try {
            DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
            dt.setRowCount(0);
            myConnection();
            
            rs=st.executeQuery(data);
            int i=0,sq=0;
            while(rs.next())
            {
                i++;
                panelID.setText(rs.getString(1));
                panelDate.setText(rs.getString(2));
                
                
                int subtotal=rs.getInt(4)*rs.getInt(5)-rs.getInt(6);
                String mm=setNameInTable(rs.getString(3));
                dt.addRow(new Object[]{i,mm,rs.getString(2),rs.getString(4),rs.getString(5),rs.getInt(6),subtotal});
                sq=sq+subtotal;
                
            }
            totalAmount.setText(""+sq);
            pid.setText("");
             paidamount.setText(""+sq);
            due.setText(""+0);
            
        } catch (SQLException ex) {
            Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void dataoperation(String n,String m)
    {
          try { 
                         String id=sid.getText();

             int a=st.executeUpdate(n);
            if(a>0)
            {
                JOptionPane.showMessageDialog(this,"Data"+m+" Succesful");
                String sp="SELECT `sid`,`sDate`,`pid`,`sQuantity`,`price`,`discount` FROM `sales` WHERE `sid`='"+id+"'";
                ShowData(sp);
               pname.setSelectedIndex(0);
               quant.setText("");
               uprice.setText("");
            txtdiscount.setText("");
               pname.requestFocus();
            }
            else{
                JOptionPane.showMessageDialog(this,"Data "+m+" failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    void cuDate(){
         JCalendar d=new JCalendar();
         SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
            String mm=sd.format(d.getDate());
        ((JTextField)sadate.getDateEditor().getUiComponent()).setText(mm);
        
    }
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            cuDate();
            myConnection();
            String id=sid.getText();
            int Pid=productid;
            int s=Integer.parseInt(quant.getText().toString());
            
            int p=Integer.parseInt(uprice.getText());
            int dis=(Integer.parseInt(txtdiscount.getText())*s*p)/100;
           
             
            
            String cuDate=((JTextField)sadate.getDateEditor().getUiComponent()).getText();
           String n="INSERT INTO `sales`( `sid`,`pid`,`sQuantity`,`price`,`sDate`,`discount` ) VALUES('"+id+"','"+Pid+"','"+s+"','"+p+"','"+cuDate+"','"+dis+"')"; 
            dataoperation(n,"Added");
          txtdiscount.setText(""+0);
       
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        myConnection();
            String id=sid.getText();
            int Pid=productid;
            int s=Integer.parseInt(quant.getText().toString());
            
           
            
            
          
            
           String n="delete from `sales` WHERE `sid`='"+id+"' and `pid`='"+Pid+"'"; 
            dataoperation(n,"Delete");
           
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void pnamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_pnamePopupMenuWillBecomeInvisible
        try {
            // TODO add your handling code here:
            myConnection();
             productid=0;
            String m=pname.getSelectedItem().toString();
            String data="SELECT `pid` FROM `product` WHERE `pname`='"+m+"'";
            rs=st.executeQuery(data);
            
            while(rs.next())
            {
            productid=rs.getInt(1);
            }
            
            pid.setText(productid+"");
            String q="SELECT `price` FROM `product` WHERE `pname`='"+m+"'";
             price(q);
             quant.requestFocus();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_pnamePopupMenuWillBecomeInvisible
    
    
    
    
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void quantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try {
                int b=0;
                int qn=Integer.parseInt(quant.getText());
                myConnection();
                String a=quant.getText().toString();
                String m=pname.getSelectedItem().toString();
                String data="SELECT `pQuant`,`Quantity`,`Stock` FROM `stocktest` WHERE `pname`='"+m+"'";
                rs=st.executeQuery(data);
                if(rs.next())
                {
                    if(rs.getInt(2)>0){
                        b=rs.getInt(1)-rs.getInt(2);
                        
                    }
                    else{
                        b=rs.getInt(1);
                    }
                }
                if(qn>b){
                    JOptionPane.showMessageDialog(this, "Stock isn't available");
                    quant.setText("");
                    quant.requestFocus();
                }
                else{
                    sadate.requestFocus();
                }
                pid.setText(""+b);
                
            } catch (SQLException ex) {
                Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
    }//GEN-LAST:event_quantKeyPressed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        search.setText("");
    }//GEN-LAST:event_searchMouseClicked

    private void quantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quantMouseClicked
        // TODO add your handling code here:
        quant.setText("");
    }//GEN-LAST:event_quantMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //Table selected item show in textfield
        DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
        txtdiscount.setText(d.getValueAt(jTable1.getSelectedRow(), 4).toString());
        sid.setText(panelID.getText());
        ((JTextField)sadate.getDateEditor().getUiComponent()).setText(panelDate.getText());
        quant.setText(d.getValueAt(jTable1.getSelectedRow(), 2).toString());
         uprice.setText(d.getValueAt(jTable1.getSelectedRow(), 3).toString());
       
        String m;
        m = d.getValueAt(jTable1.getSelectedRow(), 1).toString();
        pidsetData(m);
        SelectedTablevaluesetTable(m);
       
        //pid.setText(""+pidsetData(m));
        
        
    }//GEN-LAST:event_jTable1MouseClicked
    void pidsetData(String m){
        
        try {
            myConnection();
            
            productid=0;
            
            String data="SELECT `pid` FROM `product` WHERE `pname`='"+m+"'";
            rs2=st2.executeQuery(data);
            
            if(rs2.next())
            {
                //JOptionPane.showMessageDialog(this, ""+rs2.getInt(1));
                productid=rs2.getInt(1);
                pid.setText(""+productid);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
        
    }
    
    
    
    
    void SelectedTablevaluesetTable(String x){
        int p=0;
       int a=pname.getItemCount();
        for (int i = 0; i !=a; i++) {
            String m=pname.getItemAt(i).toString();
            if(m.contains(x))
            {
               p=i; 
                
            }
            
        }
        pname.setSelectedIndex(p);
       
        
        
    }
    
    
    
    void cl_panel(){
        
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        
        pname.setSelectedIndex(0);
               quant.setText("");
               uprice.setText("");
               dt.setRowCount(0);
               pname.requestFocus();
               sid.setText(""+autoid());
               int a=autoid();
               panelID.setText(""+a);
               totalAmount.setText("");
               paidamount.setText("");
               due.setText("");
    }
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cl_panel();
                        

                         
       

    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // Search pressed enter key
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
         String m=search.getText();
        String data="SELECT `sid`,`sDate`,`pid`,`sQuantity`,`price`,`discount` FROM `sales` WHERE `sid`='"+m+"'";
        ShowData(data);
        
        
            
        }
        
        
    }//GEN-LAST:event_searchKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //update operation
        //cuDate();
         myConnection();
            String id=sid.getText();
            int Pid=productid;
            int s=Integer.parseInt(quant.getText().toString());
            
            int p=Integer.parseInt(uprice.getText());
            int dis=(p*(Integer.parseInt(txtdiscount.getText())*s)/100);
            
            
          
            
           String n="update `sales` set `sQuantity`='"+s+"',`price`='"+p+"',`discount`='"+dis+"' WHERE `sid`='"+id+"' and `pid`='"+Pid+"'"; 
            dataoperation(n,"Update");
           
       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtdiscountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiscountMouseClicked
        // TODO add your handling code here:
        txtdiscount.setText("");
    }//GEN-LAST:event_txtdiscountMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
         pname.setSelectedIndex(0);
               quant.setText("");
               uprice.setText("");
               dt.setRowCount(0);
               pname.requestFocus();
               sid.setText(""+autoid());
              // int a=autoid();
               //panelID.setText(""+a);
               totalAmount.setText("");
               paidamount.setText("");
               due.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void paidamountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidamountKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(paidamount.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please!enter paid amount");
            
            
            }
            else{
            int a=Integer.parseInt(totalAmount.getText());
            int b=Integer.parseInt(paidamount.getText());
            
            int s=a-b;
            due.setText(""+s);
            
            }
            
        }
    }//GEN-LAST:event_paidamountKeyPressed

    private void paidamountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paidamountMouseClicked
        // TODO add your handling code here:
        paidamount.setText("");
    }//GEN-LAST:event_paidamountMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        addPrintdata();
      
       cl_panel();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void quantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_quantActionPerformed

    private void quantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantKeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||KeyEvent.VK_ENTER==c){
            
            evt.consume();
        }
        
    }//GEN-LAST:event_quantKeyTyped

    private void quantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_quantKeyReleased

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Date dt=new Date();
        SimpleDateFormat dtm=new SimpleDateFormat("yyyy-MM-dd");
        String g=dtm.format(date1.getDate());
       String sp="SELECT `sid`,`sDate`,`pid`,`sQuantity`,`price`,`discount` FROM `sales` WHERE `sDate` ='%"+g+"%'";
        ShowData(sp);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Date dt=new Date();
        SimpleDateFormat dtm=new SimpleDateFormat("yyyy-MM");
        String g=dtm.format(date1.getDate());
         String sp="SELECT `sid`,`sDate`,`pid`,`sQuantity`,`price`,`discount` FROM `sales` WHERE `sDate` Like'%"+g+"%'";
        ShowData(sp);
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         Date dt=new Date();
        SimpleDateFormat dtm=new SimpleDateFormat("yyyy");
        String g=dtm.format(date1.getDate());
        String sp="SELECT `sid`,`sDate`,`pid`,`sQuantity`,`price`,`discount` FROM `sales` WHERE `sDate` Like'%"+g+"%'";
        ShowData(sp);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void sidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        
          Date dt=new Date();
        SimpleDateFormat dtm=new SimpleDateFormat("yyyy-MM-dd");
        String g=dtm.format(date1.getDate());
        String e=dtm.format(enddate.getDate());
       String sp="SELECT `sid`,`sDate`,`pid`,`sQuantity`,`price`,`discount` FROM `sales` WHERE `sDate` BETWEEN '"+g+"' AND '"+e+"'";
        ShowData(sp);
       
        
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            // TODO add your handling code here:
            MessageFormat header=new MessageFormat("Nike Shoes ");
            MessageFormat footar=new MessageFormat("Report");
            
            
            jTable1.print(JTable.PrintMode.NORMAL, header, footar);
        } catch (PrinterException ex) {
            Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton13ActionPerformed
   public void setColor(JLabel panel){
       panel.setBackground(java.awt.Color.GRAY);
       
   }
   public void resetColor(JLabel panel){
       panel.setBackground(new java.awt.Color(115,163,239));
       
   }
    
    
    
    void printBill(){
        PrinterJob prJob=PrinterJob.getPrinterJob();
        prJob.setJobName("Printing.....");
        prJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if(pageIndex>0){
                    return Printable.NO_SUCH_PAGE;
                    
                    
                    
                }
                Graphics2D gp2d=(Graphics2D)graphics;
                gp2d.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
                gp2d.scale(0.5, 0.5);
                
                jPanel2.print(gp2d);
                
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
           
            return Printable.PAGE_EXISTS;
            }
        });
        boolean pp=prJob.printDialog();
        if(pp){
            try {
                prJob.print();
            } catch (PrinterException ex) {
                Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }
    
    
    
    
    void addPrintdata(){
       DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        if(dt.getRowCount()>0){
           try {
               String bill=panelID.getText();
               int item=dt.getRowCount();
               String amt=totalAmount.getText();
               String pai=paidamount.getText();
               String d=due.getText();
               String s=panelDate.getText();
               
               
               myConnection();
               String m="INSERT INTO `sales_acc`(`bill`,`item`,`sDate`,`amount`,`paid`,`due`) VALUES ('"+bill+"','"+item+"','"+s+"','"+amt+"','"+pai+"','"+d+"')";
               int a=st.executeUpdate(m);
               if(a>0){
                    printBill();
               }  
               else{
                   
                   JOptionPane.showMessageDialog(this, "isnot succesfull");
               }
           
           
           } catch (SQLException ex) {
               Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
           }
        
        
        
        
        }  
        
    }
    void price(String data)
    {
        try {
            myConnection();
            int price=0;
            String m=pname.getSelectedItem().toString();
            
            rs=st.executeQuery(data);
            while(rs.next())
            {
               price=rs.getInt(1);
            }
          uprice.setText(""+price);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(DataSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JLabel due;
    private com.toedter.calendar.JDateChooser enddate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField paidamount;
    private javax.swing.JLabel panelDate;
    private javax.swing.JLabel panelID;
    private javax.swing.JLabel pid;
    private javax.swing.JComboBox pname;
    private javax.swing.JTextField quant;
    private com.toedter.calendar.JDateChooser sadate;
    private javax.swing.JTextField search;
    private javax.swing.JTextField sid;
    private javax.swing.JLabel totalAmount;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField uprice;
    // End of variables declaration//GEN-END:variables
}
