/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mizanur Rahman
 */
public class Store_Proc extends javax.swing.JFrame {

    /**
     * Creates new form Store_Proc
     */
    public Store_Proc() {
        initComponents();
        Toolkit t=Toolkit.getDefaultToolkit();
        int w=(int)t.getScreenSize().getWidth();
        int h=(int)t.getScreenSize().getHeight();
        this.setSize(w,h);
        String m="SELECT *FROM `product`";
        showData(m);
        txtid.setText(""+autoid());
    }
Connection con=null;
CallableStatement cs=null;
PreparedStatement pst=null;
ResultSet rs=null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdetails = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Product Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 320, 150, 30);

        txtname.setBackground(new java.awt.Color(242, 242, 242));
        txtname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 51)));
        txtname.setOpaque(false);
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname);
        txtname.setBounds(320, 310, 200, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Product Price:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 380, 170, 30);

        txtprice.setBackground(new java.awt.Color(242, 242, 242));
        txtprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtprice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 51)));
        txtprice.setOpaque(false);
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice);
        txtprice.setBounds(320, 370, 200, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Product Details:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 440, 140, 30);

        txtdetails.setBackground(new java.awt.Color(233, 233, 233));
        txtdetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdetails.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 51)));
        txtdetails.setOpaque(false);
        txtdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(txtdetails);
        txtdetails.setBounds(320, 430, 200, 40);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(32, 33, 0, 75);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("insert Product");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 30, 299, 42);

        txtsearch.setBackground(new java.awt.Color(102, 102, 255));
        txtsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(204, 204, 255));
        txtsearch.setText("Search");
        txtsearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 255)));
        txtsearch.setCaretColor(new java.awt.Color(204, 204, 255));
        txtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtsearchMouseExited(evt);
            }
        });
        txtsearch.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtsearchInputMethodTextChanged(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
        });
        jPanel1.add(txtsearch);
        txtsearch.setBounds(530, 80, 302, 41);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_product_80px.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 10, 80, 70);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_search_32px_1.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(490, 90, 40, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1420, 150);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Product ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 270, 100, 30);

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(242, 242, 242));
        txtid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 51)));
        txtid.setOpaque(false);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid);
        txtid.setBounds(320, 260, 200, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/card-design-1152807.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 220, 480, 310);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Product Price", "Product Details"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(660, 220, 600, 430);

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_show_property_20px_1.png"))); // NOI18N
        jButton1.setText("SHOW ALL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 620, 140, 29);

        jButton2.setBackground(new java.awt.Color(0, 102, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_add_20px_1.png"))); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 570, 90, 29);

        jButton3.setBackground(new java.awt.Color(0, 102, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_update_20px_1.png"))); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 570, 120, 29);

        jButton4.setBackground(new java.awt.Color(0, 102, 153));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_delete_bin_20px_1.png"))); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(390, 570, 110, 29);

        jButton5.setBackground(new java.awt.Color(0, 102, 153));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_shutdown_20px_1.png"))); // NOI18N
        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(410, 620, 100, 29);

        jButton6.setBackground(new java.awt.Color(0, 102, 153));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/icons8_sync_20px.png"))); // NOI18N
        jButton6.setText("RESET");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(290, 620, 110, 29);

        setBounds(0, 0, 1436, 861);
    }// </editor-fold>//GEN-END:initComponents
void MyConnection()
    {
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject","root","");
            
        } catch (SQLException ex) {
            Logger.getLogger(SalesData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void showData(String m){
        try {
            MyConnection();
            DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
            dt.setRowCount(0);
            pst=con.prepareStatement(m);
            rs=pst.executeQuery();
            while(rs.next()){
                
                dt.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Store_Proc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    int autoid(){
         int a=0;
        try {
           
            MyConnection();
            String m="SELECT `pid`FROM `product`ORDER BY `pid` ASC";
            pst=con.prepareStatement(m);
            rs=pst.executeQuery();
            while(rs.next()){
                a=rs.getInt(1);
               
            }
            a++; 
            
        } catch (SQLException ex) {
            Logger.getLogger(Store_Proc.class.getName()).log(Level.SEVERE, null, ex);
        }
        return a;
    }
    //method finished
    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txtdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdetailsActionPerformed

    private void txtsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseClicked
        // TODO add your handling code here:
        txtsearch.setText("");
    }//GEN-LAST:event_txtsearchMouseClicked

    private void txtsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_txtsearchMouseEntered

    private void txtsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseExited
        // TODO add your handling code here:
        txtsearch.setText("Search");
        txtid.requestFocus();
    }//GEN-LAST:event_txtsearchMouseExited

    private void txtsearchInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtsearchInputMethodTextChanged
        // TODO add your handling code here:
        //txtsearch.setText("");
    }//GEN-LAST:event_txtsearchInputMethodTextChanged

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String a=txtsearch.getText().toString();
            String m="SELECT * FROM `product` WHERE `pid`='"+a+"' OR `pname`='"+a+"'";
            showData(m);

        }
    }//GEN-LAST:event_txtsearchKeyPressed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        txtid.setText(dt.getValueAt(jTable1.getSelectedRow(),0).toString());
        txtname.setText(dt.getValueAt(jTable1.getSelectedRow(), 1).toString());
        txtprice.setText(dt.getValueAt(jTable1.getSelectedRow(), 2).toString());
        txtdetails.setText(dt.getValueAt(jTable1.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String m="SELECT *FROM `product`";
        showData(m);
    }//GEN-LAST:event_jButton1ActionPerformed
void Cl_panel(){
    DefaultTableModel dt=( DefaultTableModel)jTable1.getModel();
    txtname.setText("");
    txtprice.setText("");
    txtdetails.setText("");
     txtid.setText(""+autoid());
    txtname.requestFocus();
    dt.setRowCount(0);
   
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // Insert 
            MyConnection();
            String name=txtname.getText().toString();
            String price=txtprice.getText().toString();
            String details=txtdetails.getText().toString();
            cs=con.prepareCall("{call DataTest (?,?,?)}");
            cs.setString(1, name);
            cs.setString(2, price);
            cs.setString(3, details);
            cs.execute();
            ParameterMetaData pm=cs.getParameterMetaData();
            if(pm==null){
                JOptionPane.showMessageDialog(this, "Data cann't Insert");
            }
            else{
                JOptionPane.showMessageDialog(this,"Data insert succesful");
                Cl_panel();
                 String m="SELECT *FROM `product`";
             showData(m);
             txtid.setText(""+autoid());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Store_Proc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            // update
            MyConnection();
            String id=txtid.getText().toString();
            String name=txtname.getText().toString();
            String price=txtprice.getText().toString();
            String details=txtdetails.getText().toString();
            cs=con.prepareCall("{call `Data_Update` (?,?,?,?)}");
            cs.setString(1, id);
            cs.setString(2, name);
            cs.setString(3, price);
            cs.setString(4, details);
            cs.execute();
            ParameterMetaData pm=cs.getParameterMetaData();
            if(pm==null){
                JOptionPane.showMessageDialog(this, "Error");
            }
            else{
                JOptionPane.showMessageDialog(this,"Data Update succesful");
                Cl_panel();
                 String m="SELECT *FROM `product`";
             showData(m);
             txtid.setText(""+autoid());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Store_Proc.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 try {
            // Insert 
            MyConnection();
            String id=txtid.getText().toString();
            
            cs=con.prepareCall("{call `Delete_Data` (?)}");
            cs.setString(1, id);
           
            cs.execute();
            ParameterMetaData pm=cs.getParameterMetaData();
            if(pm==null){
                JOptionPane.showMessageDialog(this, "Error");
            }
            else{
                JOptionPane.showMessageDialog(this,"Delete succesful");
                Cl_panel();
                 String m="SELECT *FROM `product`";
             showData(m);
             txtid.setText(""+autoid());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Store_Proc.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store_Proc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store_Proc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store_Proc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store_Proc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Store_Proc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtdetails;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
